import { GameCard } from '../types/game';

export const INITIAL_DECK: GameCard[] = [
  {
    id: 'card_1_vance_cargamento',
    w: 'vance',
    t: '«Mis patrullas están confiscando un cargamento tuyo en el puerto. Puedo ordenar que se pierda la llave por un precio.»',
    l: { t: 'Paga el soborno', fx: { dinero: -20, policia: -15, estres: -5 } },
    r: { t: 'Que se lo queden', fx: { dinero: 10, policia: 10, estres: 5, set: ['vance_mad'] } },
    target: 'common',
  },
  {
    id: 'card_2_lexi_vip',
    w: 'lexi',
    t: '«Tengo un VIP en la sala privada que quiere \'nieve\'. Es de la competencia, pero paga el triple. ¿Lo servimos?»',
    l: { t: 'Dáselo', fx: { dinero: 25, respeto: -10, estres: 10 } },
    r: { t: 'Échalo del club', fx: { respeto: 15, dinero: -5, estres: -5 } },
    target: 'common',
  },
  {
    id: 'card_3_ruso_yates',
    w: 'ruso',
    t: '«Me han dicho que tus chicos andan vendiendo cerca de mis yates. Eso no me hace feliz. Y no quieres verme infeliz.»',
    l: { t: 'Nos retiramos', fx: { respeto: -15, estres: -10, policia: -5 } },
    r: { t: 'El muelle es mío', fx: { respeto: 20, estres: 15, dinero: 10, set: ['guerra_ruso'] } },
    target: 'common',
  },
  {
    id: 'card_4_cody_token',
    w: 'cody',
    t: '«¡Bro! El token que lanzamos acaba de hacer un x10. ¿Hacemos el \'rug pull\' ahora y nos forramos o esperamos?»',
    l: { t: 'Vende todo', fx: { dinero: 35, respeto: -20, estres: 15 } },
    r: { t: 'Espera un poco más', fx: { dinero: -15, respeto: 5, estres: -10 } },
    target: 'common',
  },
  {
    id: 'card_5_trey_vagos',
    w: 'trey',
    t: '«Los Vagos se metieron en mi cuadra. Préstame unas automáticas y yo me encargo del ruido.»',
    l: { t: 'Dales las armas', fx: { dinero: -10, respeto: 15, policia: 20 } },
    r: { t: 'Arréglatelas solo', fx: { respeto: -15, estres: -5 } },
    target: 'partnerA_only',
  },
  {
    id: 'card_6_isa_fiscalia',
    w: 'isa',
    t: '«La fiscalía tiene a uno de tus repartidores. Piden cinco años o tu nombre. Un buen abogado puede callarlo, pero costará.»',
    l: { t: 'Paga el abogado', fx: { dinero: -25, policia: -20, respeto: 10 } },
    r: { t: 'Que se pudra', fx: { policia: 15, respeto: -25, estres: 10 } },
    target: 'common',
  },
  {
    id: 'card_7_tommy_microfono',
    w: 'tommy',
    t: '«Jefe, encontramos un micrófono en la oficina de atrás. No sé si son los federales o el Ruso.»',
    l: { t: 'Limpia todo el lugar', fx: { dinero: -15, estres: 10, policia: -10 } },
    r: { t: 'Úsalo para desinformar', fx: { estres: 15, policia: -5, respeto: 10 } },
    target: 'common',
  },
  {
    id: 'card_8_manny_infernus',
    w: 'manny',
    t: '«Tengo un Infernus robado, intacto. Si le cambio los números de serie te lo dejo barato, pero quema en las manos.»',
    l: { t: 'Cómpralo', fx: { dinero: -20, respeto: 15, policia: 10 } },
    r: { t: 'Paso', fx: { estres: -5, respeto: -5 } },
    target: 'common',
  },
  {
    id: 'card_9_broker_hotel',
    w: 'broker',
    t: '«Ese edificio abandonado en la playa... lo compramos con efectivo, hacemos un hotel boutique y lavamos millones.»',
    l: { t: 'Cierra el trato', fx: { dinero: -40, policia: -15, respeto: 20, legado: ['hotel_lavado'] } },
    r: { t: 'Muy arriesgado', fx: { estres: -5 } },
    target: 'partnerB_only',
  },
  {
    id: 'card_10_camila_escapada',
    w: 'camila',
    t: '«Estás trabajando demasiado. Vámonos en el yate este fin de semana, lejos de Vice Shores. Yo invito.»',
    l: { t: 'Vámonos', fx: { estres: -25, dinero: -10, respeto: -5 } },
    r: { t: 'No puedo dejar el negocio', fx: { estres: 15, dinero: 10, respeto: 5 } },
    target: 'partnerA_only',
  },
  {
    id: 'card_11_lexi_influencer',
    w: 'lexi',
    t: '«Un influencer famoso se desmayó en el baño del club. Tiene millones de seguidores. Si llamamos a urgencias habrá escándalo.»',
    l: { t: 'Sáquenlo por atrás', fx: { respeto: -10, estres: 15, policia: 5 } },
    r: { t: 'Llama a la ambulancia', fx: { policia: 15, estres: -10, respeto: 10 } },
    target: 'common',
  },
  {
    id: 'card_12_vance_medallas',
    w: 'vance',
    t: '«El jefe de policía quiere medallas. Necesito arrestar a alguien de tu equipo esta noche para salir en las noticias.»',
    l: { t: 'Entrégale a un novato', fx: { respeto: -20, policia: -25, estres: 5 } },
    r: { t: 'Nadie de mi equipo', fx: { policia: 30, respeto: 15, estres: 15 } },
    target: 'common',
  },
  {
    id: 'card_13_trey_callejon',
    w: 'trey',
    t: '«Los Vagos me dieron duro. Estoy sangrando en un callejón. Manda al doctor clandestino o no paso de esta noche.»',
    l: { t: 'Envía ayuda', fx: { dinero: -15, respeto: 20, estres: 5 } },
    r: { t: 'Apaga el teléfono', fx: { respeto: -25, policia: -5, estres: -10 } },
    target: 'partnerA_only',
  },
  {
    id: 'card_14_ruso_paz',
    w: 'ruso',
    t: '«Escuché que andas buscando problemas. Te ofrezco un trato de paz: tú te quedas con el sur, yo con los muelles.»',
    if: 'guerra_ruso',
    l: { t: 'Acepto el trato', fx: { estres: -20, dinero: -10, respeto: -10 } },
    r: { t: 'Quiero todo', fx: { estres: 25, respeto: 20, policia: 15 } },
    target: 'common',
  },
  {
    id: 'card_15_cody_hackeo',
    w: 'cody',
    t: '«Me hackearon, bro. Se llevaron todas nuestras wallets. A menos que me des efectivo para pagar el rescate...»',
    l: { t: 'Paga el rescate', fx: { dinero: -35, estres: 10 } },
    r: { t: 'Encuéntralos y mátalos', fx: { dinero: -10, policia: 20, respeto: 15 } },
    target: 'common',
  },
  {
    id: 'card_16_isa_testimonio',
    w: 'isa',
    t: '«Vance está testificando ante asuntos internos. Si le pagamos al juez adecuado, su testimonio desaparece.»',
    if: 'vance_mad',
    l: { t: 'Hazlo', fx: { dinero: -30, policia: -30, estres: -10 } },
    r: { t: 'Demasiado caro', fx: { policia: 20, estres: 15 } },
    target: 'common',
  },
  {
    id: 'card_17_tommy_dea',
    w: 'tommy',
    t: '«Hay una redada de la DEA en tres horas. Tenemos que quemar toda la mercadería y los discos duros.»',
    l: { t: 'Quema todo', fx: { dinero: -30, policia: -20, estres: 15 } },
    r: { t: 'Salva los discos', fx: { dinero: 10, policia: 35, estres: 25 } },
    target: 'common',
  },
  {
    id: 'card_18_manny_gps',
    w: 'manny',
    t: '«Encontré un rastreador GPS bajo tu deportivo. Alguien te sigue. Puedo ponérselo a un camión de basura.»',
    l: { t: 'Buena idea', fx: { policia: -15, dinero: -5, estres: -5 } },
    r: { t: 'Quiero ver quién es', fx: { estres: 15, policia: 5 } },
    target: 'common',
  },
  {
    id: 'card_19_camila_futuro',
    w: 'camila',
    t: '«Si sigues así, no llegarás a fin de año. Vende tu parte del club y vivamos tranquilos.»',
    l: { t: 'Pensaré en el futuro', fx: { estres: -30, dinero: 20, respeto: -20 } },
    r: { t: 'El club es mío', fx: { estres: 20, respeto: 15 } },
    target: 'partnerA_only',
  },
  {
    id: 'card_20_broker_alcalde',
    w: 'broker',
    t: '«El alcalde quiere un \'donativo\' para su campaña de reelección. A cambio, los permisos de obra volarán.»',
    l: { t: 'Donar generosamente', fx: { dinero: -25, policia: -15, respeto: 10 } },
    r: { t: 'No financio políticos', fx: { policia: 15, respeto: -5, estres: 5 } },
    target: 'partnerB_only',
  },
  {
    id: 'card_21_lexi_bebida',
    w: 'lexi',
    t: '«Quiero lanzar una bebida energética con el logo de Neon Dreams. Lavará el dinero de forma legal y brillante.»',
    l: { t: 'Financia el proyecto', fx: { dinero: -20, policia: -10, estres: 5, legado: ['bebida_legal'] } },
    r: { t: 'Pura estupidez', fx: { respeto: -5, estres: -5 } },
    target: 'common',
  },
  {
    id: 'card_22_trey_videoclip',
    w: 'trey',
    t: '«Grabamos un videoclip de trap en el barrio con tus autos. Se hizo viral. La policía ahora conoce nuestras caras.»',
    l: { t: 'Al menos hay respeto', fx: { respeto: 25, policia: 20, estres: 10 } },
    r: { t: 'Borra ese video', fx: { respeto: -15, estres: -5, dinero: -5 } },
    target: 'common',
  },
  {
    id: 'card_23_vance_fib',
    w: 'vance',
    t: '«FIB en la ciudad. Tipos de traje, lentes de sol, sin sentido del humor. Cierra todo por esta semana.»',
    l: { t: 'Bajar persianas', fx: { dinero: -25, policia: -20, estres: -10 } },
    r: { t: 'El negocio no para', fx: { policia: 25, dinero: 15, estres: 15 } },
    target: 'common',
  },
  {
    id: 'card_24_ruso_submarino',
    w: 'ruso',
    t: '«Tengo un submarino en alta mar. Lleno. Pero no puedo acercarlo a la costa. Necesito tus lanchas rápidas.»',
    l: { t: 'Manda los chicos', fx: { dinero: 35, policia: 20, estres: 15, respeto: 10 } },
    r: { t: 'Muy peligroso', fx: { respeto: -10, estres: -5 } },
    target: 'common',
  },
  {
    id: 'card_25_cody_maletero',
    w: 'cody',
    t: '«Me han secuestrado, bro. Literalmente estoy en un maletero. Quieren 50K en Crypto o me tiran al mar.»',
    l: { t: 'Transfiere los fondos', fx: { dinero: -25, respeto: 10, estres: -5 } },
    r: { t: 'Adiós, bro', fx: { estres: 5, respeto: -15, policia: -10 } },
    target: 'common',
  },
  {
    id: 'card_26_isa_perro',
    w: 'isa',
    t: '«Si creamos un fideicomiso a nombre de tu perro, el IRS nunca podrá confiscar esos activos.»',
    l: { t: 'Firma los papeles', fx: { dinero: -10, policia: -15, estres: -5 } },
    r: { t: 'No es necesario', fx: { estres: 5 } },
    target: 'common',
  },
  {
    id: 'card_27_manny_hollywood',
    w: 'manny',
    t: '«Vino un tipo de Hollywood. Quiere alquilar nuestro garaje clandestino para filmar una peli de acción.»',
    l: { t: 'Cóbrale el triple', fx: { dinero: 20, policia: 10, estres: 5 } },
    r: { t: 'Dile que se largue', fx: { estres: -5, respeto: 5 } },
    target: 'common',
  },
  {
    id: 'card_28_tommy_soplon',
    w: 'tommy',
    t: '«Atrapé al soplón. Trabajaba en la barra de Neon Dreams. ¿Qué hacemos con él? Lexi dice que lo perdonemos.»',
    l: { t: 'Acaba con él', fx: { respeto: 20, policia: 15, estres: 10, legado: ['miedo_calle'] } },
    r: { t: 'Échalo de la ciudad', fx: { respeto: -10, policia: -5, estres: -5 } },
    target: 'common',
  },
  {
    id: 'card_29_camila_pistola',
    w: 'camila',
    t: '«Encontré una pistola bajo la almohada. Si vamos a vivir así, al menos enséñame a usarla.»',
    l: { t: 'Enséñale a disparar', fx: { estres: 5, respeto: 5, dinero: -5 } },
    r: { t: 'Es solo para asustar', fx: { estres: 10, respeto: -5 } },
    target: 'partnerA_only',
  },
  {
    id: 'card_30_broker_desplome',
    w: 'broker',
    t: '«El mercado inmobiliario se desplomó. Nuestras inversiones en condominios no valen nada.»',
    l: { t: 'Quema los edificios', fx: { dinero: 15, policia: 20, estres: 15 } },
    r: { t: 'Asume la pérdida', fx: { dinero: -30, estres: -5 } },
    target: 'partnerB_only',
  },
];
